# Loads default set of integrations. Do not remove.
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.42.0.0/16
    - 10.42.1.0/24
    - 192.168.0.200
    - 192.168.0.20
    - 192.168.0.21
    - 192.168.0.22
    - 192.168.0.23
    - 192.168.0.24
    - ::1
# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

recorder:
  db_max_retries: 3
  commit_interval: 5
  exclude:
    entity_globs:
      - light.*

homeassistant:
  media_dirs:
    media: /media/media
    recording: /media/recordings
      
sonos:
  media_player:
    advertise_addr: 192.168.0.200
    hosts:
      - sonos.$DOMAIN_NAME
 
ffmpeg: 
 
camera:
 - platform: xiaomi_cloud_map_extractor
   host: 192.168.0.32
   token: !secret xaomi_token
   username: !secret gmail_username
   password: !secret xaomi_password
   draw: ['all']
   attributes:
     - calibration_points
 
automation: !include automations.yaml
influxdb: !include influx.yaml
mqtt: !include mqtt.yaml
rest: !include restful.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
template: !include templates.yaml
utility_meter: !include el-meter.yaml
sensor: !include sensors.yaml
