alias: Elec - Electricity Price Consumption Toggle
description: Toggles stuff on and off dependent upon current electricity price.
triggers:
  - value_template: >-
      {{ ( states('sensor.postmaster_electricity_price') | float(0) <=
      states('input_number.electricity_ceiling') | float(0) ) and
      states('sensor.postmaster_electricity_price') !=  'unavailable'  }}
    id: cheap
    alias: Becomes cheap
    trigger: template
  - entity_id:
      - sensor.carcharger_status
    from: disconnected
    to: null
    id: reconnected
    alias: Reconnected
    trigger: state
  - id: expensive
    value_template: >-
      {{ ( states('sensor.postmaster_electricity_price') | float(0) >
      states('input_number.electricity_ceiling') | float(0) ) or
      is_state('sensor.postmaster_electricity_price', 'unavailable' ) }}
    alias: Becomes expensive
    trigger: template
  - trigger: state
    entity_id:
      - sensor.carcharger_status
    to: charging
    id: Charging
    alias: Starts Charging
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: cheap
        sequence:
          - data: {}
            response_variable: startResponse
            action: script.start_car_charger
      - conditions:
          - condition: trigger
            id: expensive
        sequence:
          - if:
              - condition: state
                entity_id: sensor.carcharger_status
                state: charging
            then:
              - data:
                  charger_id: $CHARGER_ID
                  action_command: stop
                action: easee.action_command
          - alias: Set Current For Charger
            data:
              charger_id: EHTREFV2
              current_p1: 5
              current_p2: 5
              current_p3: 5
              time_to_live: 0
            action: easee.set_circuit_dynamic_limit
      - conditions:
          - condition: trigger
            id: reconnected
          - condition: template
            value_template: >-
              {{ ( states('sensor.postmaster_electricity_price') | float(0) <=
              states('input_number.electricity_ceiling') | float(0) ) and
              states('sensor.postmaster_electricity_price') !=  'unavailable' 
              }}
            alias: Test if cheap
        sequence:
          - data: {}
            action: script.start_car_charger
        alias: Reconnected and Cheap
      - conditions:
          - condition: trigger
            id: reconnected
          - condition: template
            value_template: >-
              {{ ( states('sensor.postmaster_electricity_price') | float(0) >
              states('input_number.electricity_ceiling') | float(0) ) or
              states('sensor.postmaster_electricity_price') ==  'unavailable' 
              }}
            alias: Test if expensive
        sequence:
          - action: easee.action_command
            metadata: {}
            data:
              charger_id: $CHARGER_ID
              action_command: stop
        alias: Reconnected and Expensive
      - conditions:
          - condition: trigger
            id:
              - Charging
          - condition: template
            value_template: >-
              {{ ( states('sensor.postmaster_electricity_price') | float(0) >
              states('input_number.electricity_ceiling') | float(0) ) or
              states('sensor.postmaster_electricity_price') ==  'unavailable' 
              }}
            alias: Is expensive
        sequence:
          - action: easee.action_command
            metadata: {}
            data:
              charger_id: $CHARGER_ID
              action_command: stop
    default:
      - action: easee.action_command
        metadata: {}
        data:
          charger_id: $CHARGER_ID
          action_command: stop
mode: single
trace:
  stored_traces: 10
