# Allow fallback to lower offline limit if connection is lost. Prevent main fuse blowing.
# Fuse size 25 Amp
# Max allowed current 23 Amp
alias: Elec - Load Balancer
description: Perform Load Balancing of Car Charger
mode: single
max_exceeded: silent
triggers:
  - entity_id:
      - sensor.elec_meter_elec_meter_current_l1
    id: currentchange
    trigger: state
  - entity_id:
      - sensor.elec_meter_elec_meter_current_l2
    id: currentchange
    trigger: state
  - entity_id:
      - sensor.elec_meter_elec_meter_current_l3
    id: currentchange
    trigger: state
conditions:
  - condition: state
    entity_id: sensor.carcharger_status
    state: charging
  - condition: numeric_state
    entity_id: sensor.carcharger_dynamic_circuit_limit
    attribute: state_dynamicCircuitCurrentP1
    above: 6
actions:
  - data:
      charger_id: $CHARGER_ID
      time_to_live: 1
      current_p1: >-
        {% set charge = 25 - (states('sensor.elec_meter_elec_meter_current_l1')
        | int(25) | round(0,'ceil'))
                           + (state_attr('sensor.carcharger_dynamic_circuit_limit','state_dynamicCircuitCurrentP1') | int(16) | round(0,'ceil')) %}
        {% if charge > 16 %} {{   16   }} {%- else -%} {{ charge }} {%- endif %}
      current_p2: >-
        {% set charge = 25 - (states('sensor.elec_meter_elec_meter_current_l2')
        | int(25) | round(0,'ceil'))
                           + (state_attr('sensor.carcharger_dynamic_circuit_limit','state_dynamicCircuitCurrentP2') | int(16) | round(0,'ceil')) %}
        {% if charge > 16 %} {{   16   }} {%- else -%} {{ charge }} {%- endif %}
      current_p3: >-
        {% set charge = 25 - (states('sensor.elec_meter_elec_meter_current_l3')
        | int(25) | round(0,'ceil'))
                           + (state_attr('sensor.carcharger_dynamic_circuit_limit','state_dynamicCircuitCurrentP3') | int(16) | round(0,'ceil')) %}
        {% if charge > 16 %} {{   16   }} {%- else -%} {{ charge }} {%- endif %}
    action: easee.set_circuit_dynamic_limit
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
